Version 1.0 Release Candidate 1 (#1)
* [Documentation] Add coveralls coverage badge.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Documentation] Track README.md again.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] Dotfiles, CI/CD and code quality tools

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] Dotfiles, code quality and CI/CD tools

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] Service templates

- service configuration templates for:
  - `sytemd`
  - `upstart`
  - `sysvinit`
  - `sysconfig`
- for platforms:
  - `amazonlinux-2`
  - `debian-9`
  - `amazonlinux`
  - `centos-7`
  - `fedora-latest`
  - `ubuntu-16.04`
  - `ubuntu-18.04`

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] Policyfiles for cookbook and integration.

- Policyfile.lock.json records the pass environment
- Tracks Policyfile and installed state
- No known side effects

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] Library files Ignite and service config

- These files allow binary file and service install
- These constitute the Library cookbook logic
- No known side effects

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] Unit and integration tests

- Allow integration tests and faster unit tests
- Verification of installs across platforms
- No known side effects

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Remove] Dokken and config files.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] Changelog unreleased details

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] Inspec profile skeleton and test-kitchen suite

- Harden and verify hardness of micro-VMs
- Inspec profile is a wrapper for dev-sec profiles.
- No known side effects.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* git subrepo clone (merge) https://github.com/dev-sec/linux-baseline inspec/profiles/linux-baseline

subrepo:
  subdir:   "inspec/profiles/linux-baseline"
  merged:   "1233a13"
upstream:
  origin:   "https://github.com/dev-sec/linux-baseline"
  branch:   "master"
  commit:   "1233a13"
git-subrepo:
  version:  "0.4.1"
  origin:   "https://github.com/ingydotnet/git-subrepo.git"
  commit:   "a04d8c2"
Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] [Infra] Smoke integration test

Why is it necessary? (Bug fix, feature, improvements?)

- Confirm a working installation recipe.

How does the change address the issue?

- Adds Inspec controls to verify install.
- Ignite 0.6.3 is not yet working

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] [Config] Kernel and env settings

Why is it necessary? (fix, feature, improvements?)

- Fulfill Ignite requirements.

How does the change address the issue?

- Add kernel module `br_netfilter`.
- Add environment variables.

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Fix] [Config] Typos & git config

Why is it necessary? (fix, feature, improvements?)

- Signify sign commits as notes.

How does the change address the issue?

- Confgires Git to sign using `signify-notes`.

What side effects does this change have?

- Add Note to parent commit with signature for child.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Evolve] [Auto] Docker not installed by default

Why is it necessary? (fix, feature, improvements?)

- Docker daemon is a point of weakness.

How does the change address the issue?

- No longer install Docker by default.

What side effects does this change have?

- Docker daemon is no longer available of host machine.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Refactor] [Auto] Rubocop lint changes & cleanup

Why is it necessary? (fix, feature, improvements?)

- Improve QA with code consistency.

How does the change address the issue?

- Rubocop enfoces consistentcy

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Evolve] [Auto] Retire Dokken test environment

Why is it necessary? (fix, feature, improvements?)

- The integration test env should be close as possible to production.

How does the change address the issue?

- Removes Docker base test environment.

What side effects does this change have?

- Dockken test environemnt no longer available.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Refactor] [Auto] Export CNI version data

Why is it necessary? (fix, feature, improvements?)

- CNI is installed from released binary, which changes.

How does the change address the issue?

- Exports the variable to build URL.

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Fix] [Auto] CNI download and install script

Why is it necessary? (fix, feature, improvements?)

- CNI is updated from archives

How does the change address the issue?

- Export CNI version number.

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add/Evolve/Fix/Refactor] [API/Auto/Doc/Infra/Sec/Web] Summary

Why is it necessary? (fix, feature, improvements?)

-

How does the change address the issue?

-

What side effects does this change have?

-

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Fix] [Auto] Correct manifest format

Why is it necessary? (fix, feature, improvements?)

- YAML format prevented Vm from loading

How does the change address the issue?

- Uses JSON format

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] [Doc] License & Copyright

Why is it necessary? (fix, feature, improvements?)

- Grant Apache 2.0 License.

How does the change address the issue?

- Makes the code opensource.

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Fix] [Auto] Rubocop linting now correct

Why is it necessary? (fix, feature, improvements?)

- Linting with hooks requires a clean start point.

How does the change address the issue?

- Clears all rubocop obejctions.

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Refactor] [Doc] Remove stale files

Why is it necessary? (fix, feature, improvements?)

- Rubocop hooks are now green. Backups not required.

How does the change address the issue?

- Removes stale Rubocop files.

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Fix] [Auto] Constrain coveralls breaks Circleci

Why is it necessary? (fix, feature, improvements?)

- Circle CI breaks with error:
undefined method `coverage' for #<SimpleCov::SourceFile:...>

How does the change address the issue?

- Constrain coveralls version. As suggested ManageIQ:
 https://github.com/ManageIQ/manageiq/pull/19810

What side effects does this change have?

- Many gems have their versions stepped down.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Fix] [Auto] Rubygems tar bug breaks CircleCI

Why is it necessary? (fix, feature, improvements?)

- Without this fix builds break with error:
ArgumentError:
#   "\x80\x00\x00\x00d\x9E\xD3\xD9" is not an octal string

How does the change address the issue?

- Implements suggested fix:
https://github.com/sous-chefs/line/issues/
92#issuecomment-424349172

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Fix] [Auto] CI test style only

Why is it necessary? (fix, feature, improvements?)

- CircleCI is complex wrt building chef enviornment.
- Chef's code coverage is being deprecated.
- Integration tests are the only reliable test.
- Integration tests use cloud account$.
- Developers are required to run integration tests before merging.

How does the change address the issue?

- Removes Chef unit tests

What side effects does this change have?

- Faster CI times.
- Developer responsible for running integration tests.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>

* [Add] [Doc] Note costs & signify use in docs

Why is it necessary? (fix, feature, improvements?)

- To encourage users to test the installation against
  various distribution releases.
- To alert them to the cost implications of running soome of the
  code in this repository.

How does the change address the issue?

- Document and warn.
- Describe `signify-notes` workflow.
- Provide `signify-notes` script.
- Alert users to cost responsibility of the itegration tests.
- Note usage examples for this cookbook library.
- Remove readme-dev.

What side effects does this change have?

- None.

Signed-off-by: Begley Brothers Inc <begleybrothers@gmail.com>

Co-authored-by: Taqtiqa Administrator <1335713+taqtiqa-admin@users.noreply.github.com>