[Fix] [Auto] Constrain coveralls breaks Circleci
Why is it necessary? (fix, feature, improvements?)

- Circle CI breaks with error:
undefined method `coverage' for #<SimpleCov::SourceFile:...>

How does the change address the issue?

- Constrain coveralls version. As suggested ManageIQ:
 https://github.com/ManageIQ/manageiq/pull/19810

What side effects does this change have?

- Many gems have their versions stepped down.

Signed-off-by: Begley Brothers Inc <BegleyBrothers@gmail.com>